### ISSUE TITLE
No longer builds for wasm as of v1.1

### ISSUE THREAD

**Issue by brunocodutra** [proptest-rs/proptest#321]
Build fails with the error below on v1.1. This regression was most likely introduced with 9c4647aae8ca9e4e67ef25e89a7ee08b858b608b.

```
error[E0277]: the trait bound `u128: arbitrary::traits::Arbitrary` is not satisfied
  --> /home/bruno/.cargo/registry/src/github.com-1ecc6299db9ec823/proptest-1.1.0/src/arbitrary/non_zero.rs:25:27
   |
25 |                 FilterMap<StrategyFor<$prim>, fn($prim) -> Option<Self>>;
   |                           ^^^^^^^^^^^^^^^^^^ the trait `arbitrary::traits::Arbitrary` is not implemented for `u128`
...
40 | non_zero_impl!(NonZeroU128, u128);
   | --------------------------------- in this macro invocation
   |
   = help: the following other types implement trait `arbitrary::traits::Arbitrary`:
             f32
             f64
             i16
             i32
             i64
             i8
             isize
             u16
           and 4 others
   = note: this error originates in the macro `non_zero_impl` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by matthew-russo** [comment]
I'm able to reproduce this with:
```
 cargo test --target wasm32-unknown-emscripten --no-default-features --features std -Zbuild-std
```

also related
https://github.com/proptest-rs/proptest/issues/226

**Comment by matthew-russo** [comment]
I put out a PR that should fix this, do you mind giving it a pull and seeing if your build is fixed? i'm not sure if i have the wasm builds set up properly

we should also look in to getting wasm builds in to CI but we can deal with that separately

**Comment by brunocodutra** [comment]
That works, thanks for the quick turnaround!

For the record, tested with this.

```
proptest = { git = "https://github.com/matthew-russo/proptest.git", branch = "fix-321-nonzero-broken-wasm", default-features = false, features = ["std"] }
```

**Comment by cameron1024** [comment]
Hmm, do we not have CI for WASM? If not, that seems like something we'd want to look into. I'm happy to investigate

**Comment by matthew-russo** [comment]
this auto-closed when the PR merged, we're planning a 1.2 release soon which will unblock things
